# Generated by Django 4.1.1 on 2022-10-03 17:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_sandi', '0003_alter_resultat_result_prescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='user',
        ),
        migrations.AddField(
            model_name='patient',
            name='clinic_patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clinicpatient_set', to='app_sandi.clinic', verbose_name='Clinque du patient'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='telcli',
            field=models.CharField(blank=True, max_length=9, validators=[django.core.validators.RegexValidator(message='Veuillez entrer un numéro de télèphone valide', regex='[0-9]{9}')], verbose_name='Télèphone clinique'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='telpro',
            field=models.CharField(blank=True, max_length=9, validators=[django.core.validators.RegexValidator(message='Veuillez entrer un numéro de télèphone valide', regex='[0-9]{9}')], verbose_name='Télèphone propriétaire'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_doctor',
            field=models.BooleanField(default=False, verbose_name='Docteur'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_infirmier',
            field=models.BooleanField(default=False, verbose_name='Infimier(e)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_technicien',
            field=models.BooleanField(default=False, verbose_name='Technicien'),
        ),
    ]
