# Generated by Django 4.1.1 on 2022-10-03 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_sandi', '0004_remove_patient_user_patient_clinic_patient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='clinic_patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_sandi.clinic', verbose_name='Clinque du patient'),
        ),
    ]
