# Generated by Django 4.1.1 on 2022-10-04 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_sandi', '0005_alter_patient_clinic_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultat',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='resultat',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Fichier résultat'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='clinic_patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_sandi.clinic', verbose_name='Clinique du patient'),
        ),
    ]
