# Generated by Django 4.1.1 on 2022-10-04 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sandi', '0006_resultat_file_resultat_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultat',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='resultats/'),
        ),
        migrations.AlterField(
            model_name='resultat',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Titre fichier résultat'),
        ),
    ]
