# Generated by Django 4.1.1 on 2022-10-05 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sandi', '0007_alter_resultat_file_alter_resultat_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultat',
            name='title',
        ),
        migrations.AlterField(
            model_name='resultat',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='resultats', verbose_name='Fichier du résultat'),
        ),
    ]
