# Generated by Django 4.1.1 on 2022-10-09 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sandi', '0008_remove_resultat_title_alter_resultat_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('examen', models.CharField(max_length=255, verbose_name='Examen')),
                ('valeur_reference', models.TextField(blank=True, max_length=255, null=True, verbose_name='valeur de reférence')),
                ('date_creation', models.DateField(auto_now_add=True, verbose_name='Date de création')),
            ],
        ),
        migrations.RemoveField(
            model_name='resultat',
            name='valeur_reference',
        ),
    ]
