# Generated by Django 4.1.1 on 2022-10-09 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sandi', '0009_reference_remove_resultat_valeur_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='examen',
            field=models.CharField(max_length=255, unique=True, verbose_name='Examen'),
        ),
    ]
