# Generated by Django 4.1.1 on 2022-10-11 23:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sandi', '0011_alter_user_managers_remove_user_is_infirmier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='telephone',
            field=models.CharField(blank=True, default='678787876', max_length=9, validators=[django.core.validators.RegexValidator(message='Veuillez entrer un numéro de télèphone valide', regex='[0-9]{9}')]),
            preserve_default=False,
        ),
    ]
